            SELECT DISTINCT *
            WHERE
              {
                        ?audioFile      a                                         mo:AudioFile;
                                        bmmo:path                                 ?path;
                                        mo:encodes                                ?signal;
             OPTIONAL { ?audioFile      bmmo:fileSize                             ?fileSize.      }

                        ?signal         a                                         mo:DigitalSignal;
                                        mo:published_as                           ?track;
                                        mo:duration                               ?duration.

                        ?track          a                                         mo:Track;
                                        rdfs:label                                ?label;
              }
            ORDER BY
                ?path
