            SELECT DISTINCT *
            WHERE
              {
                        ?record         a                                         mo:Record.
                      { ?record         bmmo:importedFrom                         ?source.        }
@fallback@      UNION { ?record         bmmo:importedFrom                         ?fallback.      }
@fallback@      MINUS { []              bmmo:alternateOf                          ?record;
@fallback@                              bmmo:importedFrom                         ?source.        }
                MINUS { ?record         bmmo:alternatePickOf                      [].             }

@artist@                ?artist         a                                         mo:MusicArtist.
@artist@              { ?record         foaf:maker                                ?artist.        }
@artist@        UNION { ?record         mo:track/foaf:maker                       ?artist.        }
@artist@        UNION { ?record         foaf:maker/rel:collaboratesWith           ?artist.        }
@artist@        UNION { ?record         mo:track/foaf:maker/rel:collaboratesWith  ?artist.        }

                        ?record         rdfs:label                                ?label.
             OPTIONAL { ?record         bmmo:diskNumber                           ?disk_number.   }
             OPTIONAL { ?record         bmmo:diskCount                            ?disk_count.    }
             OPTIONAL { ?record         mo:track_count                            ?track_count.   }
             OPTIONAL { ?record         mo:amazon_asin                            ?asin.          }
             OPTIONAL { ?record         mo:gtin                                   ?gtin.          }

@track@                 ?record         mo:track                                  ?track.

              }
            ORDER BY ?label
