        SELECT DISTINCT *
        WHERE
          {
            ?record     a                   mo:Record.
            ?record     bmmo:importedFrom   ?source.
            ?record     rdfs:label          ?label.

            OPTIONAL { ?record                mo:track_count    ?track_count. }
            OPTIONAL { ?record                mo:amazon_asin    ?asin.        }
            OPTIONAL { ?record                mo:gtin           ?gtin.        }

@track@     ?record     mo:track            ?track.

@artist@          { ?record     foaf:maker                                  ?artist. }
@artist@    UNION { ?record     mo:track/foaf:maker                         ?artist. }
@artist@    UNION { ?record     foaf:maker/rel:collaboratesWith             ?artist. }
@artist@    UNION { ?record     mo:track/foaf:maker/rel:collaboratesWith    ?artist. }
          }
        ORDER BY ?label
