SELECT *
WHERE  
  { 
    ?artist     a                   mo:MusicArtist. 
    ?artist     rdfs:label          ?label. 
    ?artist     vocab:artist_type   ?artist_type.
    ?madeEntity foaf:maker          ?artist.
  } 
ORDER BY ?label
