SELECT *
WHERE  
  { 
    ?artist     a                   mo:MusicArtist. 
    ?artist     rdfs:label          ?label. 
    ?madeEntity foaf:maker          ?artist.

    OPTIONAL
      {
        ?artist     vocab:artist_type       ?artist_type.
      }
  } 
ORDER BY ?label
